version: '3.1'
services:
  backend:
    image: ${BUILD_IMAGE:-task-queue-backend-test}
    build: .
    command: ${TEST_COMMAND}
    env_file:
    - env_tests
    environment:
      APP_FAST_START_MODE: ${APP_FAST_START_MODE}
    links:
      - devbox
    volumes:
      - .:/app
    depends_on:
      devbox-healthcheck:
        condition:
          service_healthy
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail http://devbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  devbox:
    image: healthsamurai/devbox:edge
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    env_file:
      - env_tests
    environment:
      AIDBOX_LICENSE_ID: ${TESTS_AIDBOX_LICENSE_ID}
      AIDBOX_LICENSE_KEY: ${TESTS_AIDBOX_LICENSE_KEY}
  devbox-db:
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
